#define ENV_WIFI_SSID 
#define ENV_WIFI_PASSWORD 

#define ENV_CLOUDANT_SERVER 
#define ENV_CLOUDANT_AUTH_ENDPOINT 
#define ENV_CLOUDANT_API_KEY 
#define ENV_CLOUDANT_AUTH_GRANT_TYPE 
#define ENV_CLOUDANT_DATABASE 

#define ENV_REDIS_ADDR 
#define ENV_REDIS_PORT 
#define ENV_REDIS_PASSWORD 
#define ENV_POST_FREQUENCY 

#define ENV_MQ135_PIN 
#define ENV_RATIO_MQ135_CLEAN_AIR 
#define ENV_CALIBRATION_AMPLITUDE 
#define ENV_CALIBRATION_EXPO 

#define ENV_DS18B20 
#define ENV_DHTPIN 